- name: Deploy Kubernetes objects for admin application (DEV)
  hosts: localhost
  gather_facts: no

  vars_files:
    - ../vars.yaml

  tasks:
    - name: Deploy admin-dev Deployment
      kubernetes.core.k8s:
        state: present
        namespace: eater-dev
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: admin-service-dev
            namespace: eater-dev
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: admin-service-dev
            template:
              metadata:
                labels:
                  app: admin-service-dev
                annotations:
                  co.elastic.logs/enabled: "true"
              spec:
                containers:
                  - name: admin-service-dev
                    image: docker.io/singularis314/admin-service-dev:0.1
                    imagePullPolicy: Always
                    env:
                      - name: IS_DEV
                        value: "true"
                      - name: BOOTSTRAP_SERVER
                        value: "{{ vars.BOOTSTRAP_SERVER }}"
                      - name: POSTGRES_USER
                        value: "eater_dev"
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                          secretKeyRef:
                            name: "eater-dev.eater-db-dev.credentials.postgresql.acid.zalan.do"
                            key: password
                      - name: POSTGRES_DB
                        value: "eater_dev"
                      - name: POSTGRES_HOST
                        value: "eater-db-dev.eater-dev.svc.cluster.local"
                      - name: TEST_USER_EMAIL
                        value: "{{ vars.TEST_USER_EMAIL }}"
                      - name: LOG_LEVEL
                        value: "{{ vars.LOG_LEVEL }}"
                affinity:
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                        - matchExpressions:
                            - key: kubernetes.io/hostname
                              operator: In
                              values:
                                - racoon-gpu
                tolerations:
                  - key: "gpu-only"
                    operator: "Equal"
                    value: "true"
                    effect: "NoSchedule"
    - name: Create Admin Service (DEV)
      kubernetes.core.k8s:
        state: present
        namespace: eater-dev
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: admin-service-dev
            namespace: eater-dev
          spec:
            selector:
              app: admin-service-dev
            ports:
              - name: http
                protocol: TCP
                port: 80
                targetPort: 5000
            type: LoadBalancer
            loadBalancerIP: "{{ vars.DEV.ADMIN_SERVICE_LB_IP }}"
