---
- name: "Main file workload configuration for DEV environment"
  hosts: localhost
  connection: local
  gather_facts: false
- name: Setup chater_ui (dev)
  import_playbook: ../chater_ui/dev/chater_ui.yaml
- name: Setup eater (dev)
  import_playbook: ../eater/dev/eater_anisble.yaml
- name: Setup eater_user (dev)
  import_playbook: ../eater_user/dev/eater_user.yaml
- name: Setup eater-postgres-mcp (dev)
  import_playbook: ../eater-postgres-mcp/dev/eater-postgres-mcp.yaml
- name: Setup admin_service (dev)
  import_playbook: ../admin_service/dev/admin.yaml
- name: Setup chater_auth (dev)
  import_playbook: ../chater_auth/dev/chater_auth.yaml
- name: Setup chater_dlp (dev)
  import_playbook: ../chater_dlp/dev/chater_dlp.yaml
- name: Setup creds for DLP (dev)
  import_playbook: ../dlp-secret-auth/gcp-dlp-service-account.yaml
- name: Setup chater_gemini (dev)
  import_playbook: ../chater_gemini/dev/chater_gemini.yaml
- name: Setup chater-gpr-operator (dev)
  import_playbook: ../chater-operators/chater-gpt-operator/dev/chater-gpt-operator.yaml
- name: Setup chater_gpt (dev)
  import_playbook: ../chater_gpt/dev/chater_gpt.yaml
- name: Setup chater_vision (dev)
  import_playbook: ../chater-vision/dev/chater_vision.yaml
- name: Setup load_test (dev)
  import_playbook: ../load_test/dev/load_test.yaml
- name: Setup mcpo-proxy (dev)
  import_playbook: ../mcpo-proxy/dev/eater-postgres-mcpo-proxy.yaml
- name: Setup models-processor (dev)
  import_playbook: ../models_processor/dev/models_processor.yaml
