- name: Deploy Kubernetes objects for chater application (DEV)
  hosts: localhost
  gather_facts: no

  vars_files:
    - ../vars.yaml

  tasks:
    - name: Create chater-dev Namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: chater-ui-dev
    - name: Deploy chater-dev Deployment
      kubernetes.core.k8s:
        state: present
        namespace: chater-ui-dev
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: chater-ui-dev
            namespace: chater-ui-dev
          spec:
            replicas: 1
            strategy:
              type: RollingUpdate
              rollingUpdate:
                maxUnavailable: 0
                maxSurge: 1
            selector:
              matchLabels:
                app: chater-ui-dev
            template:
              metadata:
                labels:
                  app: chater-ui-dev
                annotations:
                  co.elastic.logs/enabled: "true"
              spec:
                containers:
                  - name: chater-ui-dev
                    image: docker.io/singularis314/chater-ui-dev:0.5
                    imagePullPolicy: Always
                    ports:
                      - containerPort: 5000
                        name: chater-ui-dev
                    env:
                      - name: IS_DEV
                        value: "true"
                      - name: USERNAME
                        valueFrom:
                          secretKeyRef:
                            name: chater-ui-dev
                            key: USERNAME
                      - name: PASSWORD_HASH
                        valueFrom:
                          secretKeyRef:
                            name: chater-ui-dev
                            key: PASSWORD_HASH
                      - name: SECRET_KEY
                        valueFrom:
                          secretKeyRef:
                            name: chater-ui-dev
                            key: SECRET_KEY
                      - name: GOOGLE_APPLICATION_CREDENTIALS
                        value: /var/secrets/google/service-account.json
                      - name: SESSION_LIFETIME
                        value: "{{ vars.SESSION_LIFETIME }}"
                      - name: GCP_PROJECT_ID
                        value: "{{ vars.GCP_PROJECT_ID }}"
                      - name: BOOTSTRAP_SERVER
                        value: "{{ vars.BOOTSTRAP_SERVER }}"
                      - name: GOOGLE_OAUTH_CLIENT_ID
                        value: "{{ vars.GOOGLE_OAUTH_CLIENT_ID }}"
                      - name: GOOGLE_OAUTH_CLIENT_SECRET
                        value: "{{ vars.GOOGLE_OAUTH_CLIENT_SECRET }}"
                      - name: ALLOWED_EMAILS
                        value: "{{ vars.ALLOWED_EMAILS }}"
                      - name: EATER_SECRET_KEY
                        value: "{{ vars.EATER_SECRET_KEY }}"
                      - name: REDIS_ENDPOINT
                        value: "{{ vars.REDIS_ENDPOINT }}"
                      - name: DAILY_REQUEST_LIMIT
                        value: "30"
                      - name: MINIO_ENDPOINT
                        value: "http://{{ vars.minio.loadBalancerIP }}:9000"
                      - name: MINIO_ACCESS_KEY
                        value: "{{ vars.minio.root_user }}"
                      - name: MINIO_SECRET_KEY
                        value: "{{ vars.minio.root_password }}"
                      - name: MINIO_BUCKET_EATER
                        value: "eater"
                      - name: MINIO_BUCKET_GPHOTO
                        value: "gphoto"
                      - name: MINIO_SECURE
                        value: "false"
                      - name: POSTGRES_USER
                        value: "eater_dev"
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                          secretKeyRef:
                            name: "eater-dev.eater-db-dev.credentials.postgresql.acid.zalan.do"
                            key: password
                      - name: POSTGRES_DB
                        value: "eater_dev"
                      - name: POSTGRES_HOST
                        value: "eater-db-dev.eater-dev.svc.cluster.local"
                      - name: TEST_USER_EMAIL
                        value: "{{ vars.TEST_USER_EMAIL }}"
                      - name: LOCAL_MODEL_SERVICE_URL
                        value: "{{ vars.MODELS_PROCESSOR.LOCAL_MODEL_SERVICE_URL }}"
                      - name: LOCAL_MODEL_KAFKA_TOPIC
                        value: "{{ vars.MODELS_PROCESSOR.LOCAL_MODEL_KAFKA_TOPIC }}"
                      - name: DEFAULT_MODEL_TIER
                        value: "{{ vars.MODELS_PROCESSOR.DEFAULT_MODEL_TIER }}"
                      - name: LOG_LEVEL
                        value: "{{ vars.LOG_LEVEL }}"
                affinity:
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                        - matchExpressions:
                            - key: kubernetes.io/hostname
                              operator: In
                              values:
                                - "racoon-gpu"
                tolerations:
                  - key: "gpu-only"
                    operator: "Equal"
                    value: "true"
                    effect: "NoSchedule"
    - name: Create chater-dev Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: chater-ui-dev
            namespace: chater-ui-dev
            labels:
              app: chater-ui-dev
          spec:
            ports:
              - port: 5000
                targetPort: 5000
                name: http
                nodePort: 30601
            selector:
              app: chater-ui-dev
            type: NodePort

    - name: Create PodDisruptionBudget for chater-ui-dev
      kubernetes.core.k8s:
        state: present
        namespace: chater-ui-dev
        definition:
          apiVersion: policy/v1
          kind: PodDisruptionBudget
          metadata:
            name: chater-ui-dev-pdb
            namespace: chater-ui-dev
          spec:
            minAvailable: 1
            selector:
              matchLabels:
                app: chater-ui-dev

    - name: Create ServiceMonitor for chater-ui-dev
      tags:
        - servicemonitor
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: monitoring.coreos.com/v1
          kind: ServiceMonitor
          metadata:
            name: chater-ui-dev-monitor
            namespace: monitoring
            labels:
              app: gphoto-flask-prometheus
          spec:
            jobLabel: app
            selector:
              matchLabels:
                app: chater-ui-dev
            namespaceSelector:
              matchNames:
                - chater-ui-dev
            endpoints:
              - port: http
                path: /metrics
                interval: 30s
                scheme: http

    
    - name: Create secret for environment variables
      kubernetes.core.k8s:
        state: present
        namespace: chater-ui-dev
        kind: Secret
        name: chater-ui-dev
        resource_definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: chater-ui-dev
            namespace: chater-ui-dev
          data:
            USERNAME: "{{ vars.USER | b64encode }}"
            PASSWORD_HASH: "{{ vars.PASSWORD | b64encode }}"
            SECRET_KEY: "{{ vars.SECRET_KEY | b64encode }}"
    
