apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eater-prod
  namespace: argocd
spec:
  project: dev-project
  source:
    repoURL: 'https://github.com/singularis/chater.git'
    targetRevision: env/prod
    path: eater/k8s/overlays/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: eater
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
