apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eater-postgres-mcp-dev
  namespace: argocd
spec:
  project: dev-project
  source:
    repoURL: 'https://github.com/singularis/chater.git'
    targetRevision: env/dev
    path: eater-postgres-mcp/k8s/overlays/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: eater-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
