# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: modify_food_record.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'modify_food_record.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18modify_food_record.proto\x12\x05\x45\x61ter\"\xdd\x01\n\x17ModifyFoodRecordRequest\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x12\n\nuser_email\x18\x02 \x01(\t\x12\x12\n\npercentage\x18\x03 \x01(\x05\x12\x14\n\x0cis_try_again\x18\x04 \x01(\x08\x12\x18\n\x10manual_food_name\x18\x05 \x01(\t\x12\x16\n\x0emanual_insight\x18\x06 \x01(\t\x12\x19\n\x11manual_components\x18\x07 \x03(\t\x12\x10\n\x08image_id\x18\x08 \x01(\t\x12\x17\n\x0f\x61\x64\x64\x65\x64_sugar_tsp\x18\t \x01(\x02\"+\n\x18ModifyFoodRecordResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'modify_food_record_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODIFYFOODRECORDREQUEST']._serialized_start=36
  _globals['_MODIFYFOODRECORDREQUEST']._serialized_end=257
  _globals['_MODIFYFOODRECORDRESPONSE']._serialized_start=259
  _globals['_MODIFYFOODRECORDRESPONSE']._serialized_end=302
# @@protoc_insertion_point(module_scope)
