apiVersion: v1
kind: Namespace
metadata:
  name: chater-vision-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chater-vision-dev
  namespace: chater-vision-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chater-vision-dev
  template:
    metadata:
      annotations:
        co.elastic.logs/enabled: 'true'
      labels:
        app: chater-vision-dev
    spec:
      containers:
      - env:
        - name: IS_DEV
          value: 'true'
        - name: VISION_API_KEY
          valueFrom:
            secretKeyRef:
              key: VISION_API_KEY
              name: chater-vision-dev
        - name: BOOTSTRAP_SERVERS
          value: '{{ vars.BOOTSTRAP_SERVER }}'
        - name: LOG_LEVEL
          value: '{{ vars.LOG_LEVEL }}'
        image: docker.io/singularis314/chater-vision
        imagePullPolicy: Always
        name: chater-vision-dev
---
apiVersion: v1
data:
  VISION_API_KEY: '{{ vars.GEMINI_API_KEY | b64encode }}'
kind: Secret
metadata:
  name: chater-vision-dev
  namespace: chater-vision-dev
