apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: chater-auth-dev
nameSuffix: -dev

images:
- name: docker.io/singularis314/chater-auth
  newName: docker.io/singularis314/chater_auth
  newTag: dev-latest
- name: docker.io/singularis314/chater_auth
  newName: docker.io/singularis314/chater_auth
  newTag: dev-6044b7d

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "true"
  target:
    kind: Deployment
    name: chater-auth
