apiVersion: v1
kind: Namespace
metadata:
  name: chater-auth-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chater-auth-dev
  namespace: chater-auth-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chater-auth-dev
  template:
    metadata:
      annotations:
        co.elastic.logs/enabled: 'true'
      labels:
        app: chater-auth-dev
    spec:
      containers:
      - env:
        - name: IS_DEV
          value: 'true'
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: JWT_SECRET
              name: chater-auth-dev
        - name: GOOGLE_CLIENT_ID
          value: '{{ vars.GOOGLE_CLIENT_ID }}'
        - name: APPLE_BUNDLE_ID
          value: '{{ vars.APPLE_BUNDLE_ID }}'
        - name: JWT_EXPIRATION_HOURS
          value: '{{ vars.JWT_EXPIRATION_HOURS }}'
        - name: BOOTSTRAP_SERVERS
          value: '{{ vars.BOOTSTRAP_SERVER }}'
        - name: LOG_LEVEL
          value: '{{ vars.LOG_LEVEL }}'
        image: docker.io/singularis314/chater_auth
        imagePullPolicy: Always
        name: chater-auth-dev
---
apiVersion: v1
data:
  JWT_SECRET: '{{ vars.JWT_SECRET | b64encode }}'
kind: Secret
metadata:
  name: chater-auth-dev
  namespace: chater-auth-dev
