- name: Deploy Kubernetes objects for chater DLP application (DEV)
  hosts: localhost
  gather_facts: no

  vars_files:
    - ../../vars.yaml

  tasks:
    - name: Create chater-dlp-dev Namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: chater-dlp-dev
    - name: Deploy chater-dlp-dev Deployment
      kubernetes.core.k8s:
        state: present
        namespace: chater-dlp-dev
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: chater-dlp-dev
            namespace: chater-dlp-dev
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: chater-dlp-dev
            template:
              metadata:
                labels:
                  app: chater-dlp-dev
                annotations:
                  co.elastic.logs/enabled: "true"
              spec:
                containers:
                  - name: chater-dlp-dev
                    image: docker.io/singularis314/chater-dlp-dev:0.3
                    imagePullPolicy: Always
                    env:
                      - name: IS_DEV
                        value: "true"
                      - name: GOOGLE_APPLICATION_CREDENTIALS
                        value: /var/secrets/google/service-account.json
                      - name: GCP_PROJECT_ID
                        value: "{{ vars.GCP_PROJECT_ID }}"
                      - name: BOOTSTRAP_SERVER
                        value: "{{ vars.BOOTSTRAP_SERVER }}"
                      - name: LOG_LEVEL
                        value: "{{ vars.LOG_LEVEL }}"
                    volumeMounts:
                      - name: gcp-dlp-creds
                        mountPath: /var/secrets/google
                        readOnly: true
                affinity:
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                        - matchExpressions:
                            - key: kubernetes.io/hostname
                              operator: In
                              values:
                                - racoon
                volumes:
                  - name: gcp-dlp-creds
                    secret:
                      secretName: gcp-dlp-service-account
