# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chess_game.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63hess_game.proto\x12\x05\x45\x61ter\"o\n\x17RecordChessGameRequest\x12\x14\n\x0cplayer_email\x18\x01 \x01(\t\x12\x16\n\x0eopponent_email\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"`\n\x18RecordChessGameResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x0cplayer_score\x18\x02 \x01(\t\x12\x16\n\x0eopponent_score\x18\x03 \x01(\t\"*\n\x15GetChessStatsRequest\x12\x12\n\nuser_email\x18\x01 \x01(\t\"h\n\x16GetChessStatsResponse\x12\r\n\x05score\x18\x01 \x01(\t\x12\x15\n\ropponent_name\x18\x02 \x01(\t\x12\x16\n\x0elast_game_date\x18\x03 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chess_game_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECORDCHESSGAMEREQUEST._serialized_start=27
  _RECORDCHESSGAMEREQUEST._serialized_end=138
  _RECORDCHESSGAMERESPONSE._serialized_start=140
  _RECORDCHESSGAMERESPONSE._serialized_end=236
  _GETCHESSSTATSREQUEST._serialized_start=238
  _GETCHESSSTATSREQUEST._serialized_end=280
  _GETCHESSSTATSRESPONSE._serialized_start=282
  _GETCHESSSTATSRESPONSE._serialized_end=386
# @@protoc_insertion_point(module_scope)
