- name: Deploy Kubernetes objects for eater application (DEV)
  hosts: localhost
  gather_facts: no

  vars_files:
    - ../vars.yaml

  tasks:
    - name: Create eater-dev Namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: eater-dev
    - name: Deploy eater-users-dev Deployment
      kubernetes.core.k8s:
        state: present
        namespace: eater-dev
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: eater-users-dev
            namespace: eater-dev
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: eater-users-dev
            template:
              metadata:
                labels:
                  app: eater-users-dev
                annotations:
                  co.elastic.logs/enabled: "true"
              spec:
                imagePullSecrets:
                  - name: regcred
                affinity:
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                        - matchExpressions:
                            - key: kubernetes.io/hostname
                              operator: In
                              values:
                                - racoon-gpu
                tolerations:
                  - key: "gpu-only"
                    operator: "Equal"
                    value: "true"
                    effect: "NoSchedule"
                containers:
                  - name: eater-users-dev
                    image: docker.io/singularis314/eater_users-dev:0.1
                    imagePullPolicy: Always
                    env:
                      - name: IS_DEV
                        value: "true"
                      - name: BOOTSTRAP_SERVER
                        value: "{{ vars.BOOTSTRAP_SERVER }}"
                      - name: POSTGRES_USER
                        value: "eater_dev"
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                          secretKeyRef:
                            name: "eater-dev.eater-db-dev.credentials.postgresql.acid.zalan.do"
                            key: password
                      - name: POSTGRES_DB
                        value: "eater_dev"
                      - name: POSTGRES_HOST
                        value: "eater-db-dev.eater-dev.svc.cluster.local"
                      - name: EATER_SECRET_KEY
                        value: "{{ vars.EATER_SECRET_KEY }}"
                      - name: REDIS_ENDPOINT
                        value: "{{ vars.REDIS_ENDPOINT }}"
                      - name: NEO4J_URI
                        value: "bolt://neo4j.neo4j.svc.cluster.local:7687"
                      - name: NEO4J_USER
                        value: "neo4j"
                      - name: NEO4J_PASSWORD
                        valueFrom:
                          secretKeyRef:
                            name: neo4j-auth-eater
                            key: NEO4J_PASSWORD
                      - name: LOG_LEVEL
                        value: "{{ vars.LOG_LEVEL }}"
                    ports:
                      - containerPort: 8000
                        name: http
                    resources:
                      requests:
                        memory: "128Mi"
                        cpu: "100m"
                      limits:
                        memory: "256Mi"
                        cpu: "200m"
                    livenessProbe:
                      httpGet:
                        path: /health
                        port: 8000
                      initialDelaySeconds: 30
                      periodSeconds: 300
                    readinessProbe:
                      httpGet:
                        path: /ready
                        port: 8000
                      initialDelaySeconds: 5
                      periodSeconds: 15
    - name: Create eater-dev Service
      kubernetes.core.k8s:
        state: present
        namespace: eater-dev
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: eater-users-dev-internal
            namespace: eater-dev
          spec:
            selector:
              app: eater-users-dev
            ports:
              - protocol: TCP
                port: 80
                targetPort: 8000
                name: http
            type: ClusterIP

    - name: Create eater-dev Service proxy in chater-ui-dev namespace
      kubernetes.core.k8s:
        state: present
        namespace: chater-ui-dev
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: eater-users-dev-service
            namespace: chater-ui-dev
          spec:
            type: ExternalName
            externalName: eater-users-dev-internal.eater-dev.svc.cluster.local
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80
                name: http

    - name: Create eater-dev LoadBalancer Service for MetalLB
      kubernetes.core.k8s:
        state: present
        namespace: eater-dev
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: eater-users-dev-lb
            namespace: eater-dev
          spec:
            selector:
              app: eater-users-dev
            ports:
              - protocol: TCP
                port: 80
                targetPort: 8000
                name: http
            type: LoadBalancer
            loadBalancerIP: "{{ vars.DEV.EATER_USERS_LB_IP }}"
