- name: Deploy Kubernetes objects for chater application (DEV)
  hosts: localhost
  gather_facts: no

  vars_files:
    - ../vars.yaml

  tasks:
    - name: Create ChaterGpt Custom Resource (DEV)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: chater.example.com/v1
          kind: ChaterGpt
          metadata:
            name: chater-gpt-dev-operated
            namespace: chater-gpt-dev
          spec:
            namespace: chater-gpt-dev-operated
            bootstrapServer: "{{ vars.BOOTSTRAP_SERVER }}"
            model: "{{ vars.MODEL }}"
            visionModel: "{{ vars.VISION_MODEL }}"
            openAIAPIKey: "{{ vars.CAPI | b64encode }}"
            secretKey: "{{ vars.SECRET_KEY | b64encode }}"
            logLevel: "{{ vars.LOG_LEVEL }}"
            replicas: 1
            isDev: "true"
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: kubernetes.io/hostname
                          operator: In
                          values:
                            - racoon
