apiVersion: chater.example.com/v1
kind: ChaterGpt
metadata:
  name: chater-gpt-operated
  namespace: chater-gpt
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - racoon
            - racoon-gpu
  bootstrapServer: '{{ vars.BOOTSTRAP_SERVER }}'
  logLevel: '{{ vars.LOG_LEVEL }}'
  model: '{{ vars.MODEL }}'
  namespace: chater-gpt-operated
  openAIAPIKey: '{{ vars.CAPI | b64encode }}'
  replicas: 1
  secretKey: '{{ vars.SECRET_KEY | b64encode }}'
  visionModel: '{{ vars.VISION_MODEL }}'
